version: '3'

services:
    
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./excelplay-client/dist/excelplay/:/usr/share/nginx/html/
            - ./static:/var/www/static/
            - ./media:/var/www/media/
        depends_on:
            - auth1
            - kryptos
    
    auth1:
        build: ./excelplay-auth/excelplay_auth/.
        depends_on:
            - redis
            - db
        command: bash excelplay-auth/docker_entrypoint.sh
        volumes:
            - .:/excelplay/excelplay_auth
        ports:
            - "8000:8000"
        environment:
            - secret_key=$secret_key
        
    kryptos:
        build: ./excelplay-kryptos/excelplay_kryptos/.
        depends_on:
            - redis
            - db2
        command: bash excelplay-kryptos/docker_entrypoint.sh
        volumes:
            - .:/excelplay/excelplay_kryptos
            - 'staticdata:/excelplay/excelplay_kryptos/excelplay-kryptos/excelplay_kryptos/static'
        ports:
            - "8001:8001"
            
        environment:
            - secret_key=$secret_key

    db:
        container_name: 'db'
        restart: always
        image: postgres:alpine
        expose:
            - '5432'
        volumes:
            - 'pgdata:/var/lib/postgresql/data'

    db2:
        container_name: 'db2'
        restart: always
        image: postgres:alpine
        expose:
            - "5433"
        ports:
            - "5433:5432"
        volumes:
            - 'pgdata2:/var/lib/postgresql/data'
 
    
    redis:
        container_name: 'redis'
        restart: always
        image: redis
        command: redis-server
        volumes:
            - 'redisdata:/data'

volumes:
    pgdata2:
    pgdata:
    redisdata:
    staticdata:
