version: '3'

services:

    auth:
        build: ./excelplay-auth/excelplay_auth/.
        command: bash excelplay-auth/docker_entrypoint.sh
        volumes:
            - .:/excelplay/excelplay_auth
        ports:
            - "8000:8000"

    kryptos:
        build: ./excelplay-kryptos/excelplay_kryptos/.
        command: bash excelplay-kryptos/docker_entrypoint.sh
        volumes:
            - .:/excelplay/excelplay_kryptos
        ports:
            - "8001:8001"

    db:
        restart: always
        image: postgres:alpine
        expose:
            - '5432'
        volumes:
            - database:/var/lib/postgresql/data
    

volumes:
    database:
    static:
    media:
